name: pos_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # Local DB (Drift)
  drift: ^2.23.1
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0
  
  # Networking
  dio: ^5.4.1
  
  # Utils
  shared_preferences: ^2.2.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  fpdart: ^1.1.0
  uuid: ^4.5.2
  equatable: ^2.0.8
  socket_io_client: ^3.1.4
  
  # Printing
  esc_pos_utils_plus: ^2.0.0
  image: ^4.1.7 # Required by esc_pos_utils for image printing
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.8
  riverpod_generator: ^2.6.3
  drift_dev: ^2.23.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
